# .streamlit/secrets.toml
[auth]
admin_user = "andy"
admin_password = "test"

admin_user2 = "admin"
admin2_password= "test"

general_user = "cheiljedang_a"
general_password = "1234"

#[connections.gsheets]
#spreadsheet = "https://docs.google.com/spreadsheets/d/16MNzW1nsmVeTdSJGX-kIF1lYi-DK1ByJqgU953GfqjE/edit"
#type = "service_account"
#project_id = "marine-lane-298520"
#private_key_id = "97d5dabf646f2681a36e50c672d39957f746b625"
#private_key = """-----BEGIN PRIVATE KEY-----
#MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDGEGBVycyNuNep
#41Gja709UmG7hkuiiKW0zRkpsp2Sy4AONU1DaceJEhuI+Xjw9mUcBjRrMr8A8fJP
#KZmgeWZz5QPS3Km84JNcWYoqgNr8an2e8fWPYF/h3hwUyU65hXPPiAvPI9nb+jlP
#cMKB+E8fEmtAfImGfKeT+bEy9Z6vlH+BoaCO64+JTfAwvHBq4trgfV7lmCFGsqEL
#nmaB86ZsLpAVgxl29Kc1hAgz7mrW2cLU3SdktfWgJ463Kq+Hd+5FxNXi0zkO4N9M
#cHoHlHKCgu2Urz5I2sK5RVRJJEu1p8dBDfWRYxxzv3r1NXEBPbApirGPbp8fYnfO
#buwHgFodAgMBAAECggEAAkAHcwDo3Im+TA1CdlntvcQjplCOug66JTQUSuyoOrEX
#8TqF3N0ph2e6FEh31vL2OSusckcuDxwnaRmbWgOcxgilDkwYibPjlUIJlTCIEO0e
#Eijf5dV7ooS62HCbvuK+D5xC84MXE44WExeAUQ0JpxMJYxpXGA8lsYNG2y+Z8k3l
#EVhpDB58/SddIupc43i6tfPT1fdcqeSmHkHHHLUcjmybR2JF33sR7cXMQt8NBQ2X
#ZA/RWtcUsAbXQNbj3EyQ6OvUx2TIRX+d0m7atgMJmdV4fY58LfCqgkW4y0IiKQye
#oqlYOneii9zyowIbceus1LGKAUvnaSUpYgHQ4yDsCQKBgQDnpwn4DLt9XhLf90/r
#YE8PbeOj15bfqLPKIa1ZCM81K0GwsB9jX6PeFn2kuSbaOaXfKgR89szXd4hYfREq
#0wTRza86dA7hp9qcDwkLREMZFVDbTTmbdkpFaHoyaea+GjNVnVs8wydgxvafA69e
#xxj8RfXSQe7Q7VQ4Q4uUAxvD1QKBgQDa4ZZVAdAzfzb8IvOtwdPFnRNy2IswaUS4
#hDnLf4ZSMpZzQxxTW+ss9kzmkjzKNUayaLI7znDZy8ziBdYIYQuB1QWpD05ih537
#T70fKUdW18Xu502+SBmJ+QwxdkvjIrhsby8FQGK0d6ByJ5HgQ0NNxv1LRoGjOTCi
#fESZuL2JKQKBgQDUcB43SU3jkZMTq1SyUXcPekIprfshjy+Z7bpwDSEg7FNouot+
#cWXwtIVyu41C0V0pQ/ors5V0/5ydMcy9jhk8YjkRDP/ctzdGqI8tsuMprJ+jDbYH
#uLox3rc5Zl8B9Tsgh5b1KS8ClFP0zcdUzpc+OtZNhMOC/DKhCmiFSzh6JQKBgQCp
#XlYNgVGyB4ZspD8a/Rj5mQornBRYaZybivWN2if+AtcYaZ3Jgx7/s7bd09rmPUNv
#WkRQsvXwEht/6jQsV6un00aGAyoMZBSDGrilHDPvpxeqPaGS1AevE9+zhm5CW+OJ
#RJ+F2MSIEOk+bBAdEO9Lh+cIEI7P1rkjgjUzHhjLwQKBgQCpm6GM7qqr64vyweyz
#UnOK1AFg844ewAltxCR6FhOKzVoiARJpTj5SJ41/YRyOfRa1Bq/a9E5aMJX2S3zU
#80p2OSRpFJ8ryBb8tMdVD53vJOg1tRFhxBCImioJQuCn4aiJEUvWTtxse6v6bKR8
#z2lwpCjIvZpjaC/FevRSNN45jQ==
#-----END PRIVATE KEY-----"""
#client_email = "tennis-manager@marine-lane-298520.iam.gserviceaccount.com"
#client_id = "101053623248355195790"
#auth_uri = "https://accounts.google.com/o/oauth2/auth"
#token_uri = "https://oauth2.googleapis.com/token"
#auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
#client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tennis-manager%40marine-lane-298520.iam.gserviceaccount.com"
#universe_domain = "googleapis.com"
#
#[credentials.usernames.andy]
#name = "Andy"
#password = "test"
#
#[credentials.usernames.admin]
#name = "Admin"
#password = "test"
#
#[credentials.usernames.cheiljedang_a]
#name = "General User"
#password = "1234"
#
#[cookie]
#expiry_days = 30
#key = "cj_tennis_secret_key"
#name = "tennis_auth_cookie"
#
#[preauthorized]
#emails = []